
#macro FRACTURE_FADE_ENABLED true
#macro FRACTURE_FADE_SETTLED true
#macro FRACTURE_FADE_DELAY_FROM 45
#macro FRACTURE_FADE_DELAY_TO 60
#macro FRACTURE_FADE_SPEED_FROM 0.008
#macro FRACTURE_FADE_SPEED_TO 0.015
