
#macro FRACTURE_BENCHMARK true

#macro FRACTURE_COLLISION_GROUP 1
#macro FRACTURE_DENSITY 0.5
#macro FRACTURE_RESTITUTION 0
#macro FRACTURE_FRICTION 0.2
#macro FRACTURE_LINEAR_DAMPING 0.1
#macro FRACTURE_ANGULAR_DAMPING 0.1

#macro FRACTURE_FADE_ENABLED true
#macro FRACTURE_FADE_SETTLED true
#macro FRACTURE_FADE_DELAY_FROM 30
#macro FRACTURE_FADE_DELAY_TO 45
#macro FRACTURE_FADE_SPEED_FROM 0.01
#macro FRACTURE_FADE_SPEED_TO 0.02
