
#macro FRACTURE_DEBUG true

#macro FRACTURE_FADE_ENABLED true
#macro FRACTURE_FADE_SETTLED true
#macro FRACTURE_FADE_DELAY_FROM 30
#macro FRACTURE_FADE_DELAY_TO 45
#macro FRACTURE_FADE_SPEED_FROM 0.01
#macro FRACTURE_FADE_SPEED_TO 0.02
